const dependencies = ["react", "react-dom", "react-router-dom", "sanitize.css"];

const devDependencies = [
    "generact",
    "eslint",
    "stylelint",
    "prettier",
    "eslint-config-prettier",
    "eslint-plugin-import",
    "eslint-plugin-simple-import-sort",
    "eslint-plugin-react",
    "eslint-plugin-react-hooks",
    "eslint-plugin-jest",
    "stylelint-config-standard",
    "stylelint-config-prettier",
    "jest",
    "@testing-library/react",
    "@testing-library/jest-dom",
    "webpack",
    "webpack-cli",
    "webpack-dev-server",
    "@babel/core",
    "babel-loader",
    "babel-preset-react-app",
    "react-hot-loader",
    "@pmmmwh/react-refresh-webpack-plugin",
    "react-refresh",
    "react-dev-utils",
    "clean-webpack-plugin",
    "html-webpack-plugin",
    "webpack-bundle-analyzer",
    "terser-webpack-plugin",
    "css-minimizer-webpack-plugin",
    "eslint-webpack-plugin",
    "mini-css-extract-plugin",
    "case-sensitive-paths-webpack-plugin",
    "fork-ts-checker-webpack-plugin",
    "file-loader",
    "url-loader",
    "svg-url-loader",
    "style-loader",
    "css-loader",
    "sass-loader",
    "postcss",
    "postcss-loader",
    "postcss-flexbugs-fixes",
    "postcss-preset-env",
];

const tsDevDependencies = [
    "typescript",
    "@types/node",
    "@types/react",
    "@types/react-dom",
    "@types/react-router-dom",
    "@types/jest",
    "@typescript-eslint/parser",
    "@typescript-eslint/eslint-plugin",
    "ts-jest",
    "@babel/preset-typescript",
    "type-fest",
];

module.exports = { dependencies, devDependencies, tsDevDependencies };
